### ISSUE TITLE
Leaderboard string issues with protocol 5

### ISSUE THREAD

**Issue by Barbosik** [Barbosik/OgarMulti#1]
Source: https://github.com/OgarProject/Ogar/issues/588#issuecomment-223647449

![Leaderboard bug](https://cloud.githubusercontent.com/assets/11600822/15787887/9beb38fe-29bc-11e6-8968-98e04c2217ec.png)

**Comment by NatsuTheGreat** [comment]
What I have found with leaderboard is that it doesn't make your name red when you're on the leadeboard.

**Comment by Barbosik** [comment]
yes, I know, currently server doesn't mark current player due to specific leaderboard implementation. There is need to rewrite code to build leaderboard per each user.

**Comment by Barbosik** [comment]
String support for protocol 5 fixed
