### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/OgarMulti#6]
Fixed.

**Comment by Barbosik** [comment]
Can you explain what did you means?
You can just select name "<shark>MyName", and you will have shark skin and name "MyName".

Could you please write your steps to reproduce, expected result and actual result?

**Comment by NatsuTheGreat** [comment]
I solved problem 1, problem 2 remains.

What I need is the skin to stay there with having to have ```<skinname>``` there all the time, that clogs up the space and doesn't allow me to put in my actual name. I need to stay there until disconnected or something. If you understand me?

**Comment by NatsuTheGreat** [comment]
Yet again fixed. Sorry I didn't look into this myself, fixed it by myself. Sorry to bother you man!
